.\" Manpage for gen.sh
.\" 
.TH man 8 "28 Jan 2020" "1.0" "Code Generation in WeGO man page"
.SH NAME
gen.sh \- Generate various types of WeGO modules.
.SH SYNOPSIS
gen.sh
.Op .Fl ? 
.Op .Fl i .Fl f .Ar filename
.SH DESCRIPTION
gen.sh is a provided util to generate varioous kinds of WeGO modules.

.SH OPTIONS
-h and -p for specifying the host name and port number for the redis server that is hosting the property database.
.br
The -l (for list) option lists all the properties available.
.br
The -d (for delete) option deletes a property.
.br
The -i (for import) option imports all the properties from a file (specified using the -f option or stdin if the -f option is not specified)
.br
All inputs for the import must be of the form prop-name=propvalue
.br
.SH POSSIBLE USAGES
$ gen.sh
Choose 1 for Workflow
.br
Choose 2 for generating
.br
$ "props -l -t t1" lists out all the properties for trajectory t1 (base properties are listed but t1 specific over-rides are also there) 
.br
$ "props -d -f file1" deletes all the properties that exist in file1. file1 must have the property names in separate lines.
.br
$ "props -i -f file1" imports all the properties from file1. file1 must have properties in separate lines in the form prop-name=prop-value
.br
$ "props -d -f file1 -t t1" deletes all the specific property over-rides for trajectory t1. It does not touch the main properties.
.br
$ "props -i -f file1 -t t1" imports all the specific property over-rides for trajectory t1. It does not touch the main properties.
.br
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Raja Shankar Kolluru
